# Generated by Django 3.2.6 on 2022-01-04 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Splint',
            fields=[
                ('id_splint', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('splint_file', models.FileField(upload_to='splint_files')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Splints',
                'db_table': 'Splint',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='splint',
            index=models.Index(fields=['id_splint'], name='Splint_id_spli_327c57_idx'),
        ),
    ]
