# Generated by Django 3.2.6 on 2022-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_splint_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splint',
            name='splint_file',
            field=models.FileField(upload_to='apps/home/media/splints'),
        ),
    ]
